# Generated by Django 5.0.7 on 2024-07-13 16:21

import url_short.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(default=url_short.models.generate_code, max_length=15, unique=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
        ),
    ]
